import streamlit as st
from ultralytics import YOLO
import cv2
from PIL import Image
import numpy as np
import os
import tempfile
import base64

st.set_page_config(page_title="Helmet Detection", layout="centered")
st.title("Helmet Detection System")

# Sidebar
st.sidebar.header("Settings")
model_choice = st.sidebar.selectbox("Select Model", ["YOLOv8s", "YOLOv11s"])
conf_threshold = st.sidebar.slider("Confidence", 0.1, 1.0, 0.45, 0.05)

model_paths = {"YOLOv8s": "model/yolo8s.pt", "YOLOv11s": "model/yolo11s.pt"}


@st.cache_resource
def load_model(path):
    return YOLO(path)


model_path = model_paths[model_choice]
if not os.path.exists(model_path):
    st.error(f"Model not found: {model_path}")
    st.stop()

model = load_model(model_path)
st.sidebar.success(f"Model Loaded: {model_choice}")

input_type = st.sidebar.radio("Input Type", ["Image", "Video"])

# ============================= IMAGE =============================
if input_type == "Image":
    uploaded = st.file_uploader(
        "Upload Image → Auto Detect", type=["jpg", "jpeg", "png"]
    )
    if uploaded:
        with st.spinner("Detecting..."):
            img = Image.open(uploaded)
            res = model(np.array(img), conf=conf_threshold, verbose=False)[0]
            result_img = res.plot()
            st.image(result_img, caption="Result", width=800)

# ============================= VIDEO =============================
else:
    uploaded_video = st.file_uploader(
        "Upload Video → Auto Process", type=["mp4", "mov", "avi", "mkv"]
    )

    if uploaded_video is not None:
        # Save uploaded video
        tfile = tempfile.NamedTemporaryFile(delete=False, suffix='.mp4')
        tfile.write(uploaded_video.read())
        input_path = tfile.name

        output_path = tempfile.NamedTemporaryFile(delete=False, suffix='.mp4').name

        try:
            with st.spinner("Processing Video... This may take a while"):
                # Use YOLO's built-in predict with stream=True and save=True
                # Yeh direct annotated video save kar deta hai without manual VideoWriter!
                model.predict(
                    source=input_path,
                    conf=conf_threshold,
                    save=True,
                    project=tempfile.gettempdir(),
                    name="prediction",
                    exist_ok=True,
                    stream=False,
                    verbose=False
                )

                # Find the output video (YOLO saves it as exp.mp4, exp0.mp4, etc.)
                pred_dir = os.path.join(tempfile.gettempdir(), "prediction")
                video_files = [f for f in os.listdir(pred_dir) if f.endswith(".mp4")]
                if not video_files:
                    st.error("No output video generated by YOLO")
                    st.stop()

                latest_video = max([os.path.join(pred_dir, f) for f in video_files], key=os.path.getctime)

                # Show the video
                with open(latest_video, "rb") as f:
                    st.video(f.read())
                st.success("Detection Complete!")

        except Exception as e:
            st.error(f"Error: {str(e)}")
            import traceback
            st.code(traceback.format_exc())
        finally:
            # Cleanup
            try:
                os.unlink(input_path)
                if 'latest_video' in locals():
                    os.unlink(latest_video)
            except:
                pass
